async (payload) => {
  const THREE=await import('/vendor/three/build/three.module.js');
  const {Environment}=await import('/environment.js');
  const {inspectObservation}=await import('/observation_camera.js');
  const scene=new THREE.Scene();scene.background=new THREE.Color('#112b36');
  scene.add(new THREE.HemisphereLight(0xffffff,0x777777,3));
  const camera=new THREE.PerspectiveCamera(60,1.5,.02,1000);
  const renderer=new THREE.WebGLRenderer({preserveDrawingBuffer:true});renderer.setSize(960,640);document.body.appendChild(renderer.domElement);
  const world={seabed_depth:20,start_pos:[0,0,10],spool:[0,0,0],world_seed:7,scenario:{key:'fixture',visibility_m:30},habitat:{entities:[{id:'coral-test',kind:'coral',variant:0,pos:[5,0,10],scale:1,yaw:0}],fish_schools:[]}};
  let environment=new Environment(scene,world),state={t:0,silt:0};
  const aim=()=>{camera.position.set(0,-9.6,0);camera.lookAt(0,-9.6,5);camera.updateMatrixWorld(true);};aim();
  const results={};
  const check=(name,predicate,...args)=>{const evidence=inspectObservation({scene,camera,environment,state,world,camMode:'onboard',...args[0]});results[name]=evidence;if(!predicate(evidence))throw new Error(name+': '+JSON.stringify(evidence));return evidence;};
  const good=check('good_coral',e=>e.ok&&e.entity_id==='coral-test');
  if(Math.abs(good.camera.pos[0])>1e-6||Math.abs(good.camera.q[0]-1)>1e-6)throw new Error('Camera FRD/NED conversion');
  renderer.render(scene,camera);window.__observationScreenshot=renderer.domElement.toDataURL('image/png');
  const wall=new THREE.Mesh(new THREE.BoxGeometry(3,3,.3),new THREE.MeshStandardMaterial());wall.position.set(0,-9.6,2.5);scene.add(wall);
  check('opaque_wall',e=>!e.ok&&!e.visible);
  wall.visible=false;check('hidden_wall',e=>e.ok);
  wall.visible=true;wall.material.transparent=true;wall.material.opacity=.1;wall.material.depthWrite=false;check('transparent_overlay',e=>e.ok);
  scene.remove(wall);wall.geometry.dispose();wall.material.dispose();
  camera.lookAt(0,-9.6,-5);check('offscreen',e=>!e.ok);aim();
  check('external_camera',e=>!e.ok&&e.view==='orbit',{camMode:'orbit'});
  const frd=new THREE.Quaternion().setFromEuler(new THREE.Euler(.2,.3,.5,'ZYX'));
  camera.quaternion.set(-frd.y,-frd.z,frd.x,frd.w).multiply(new THREE.Quaternion(0,1,0,0));
  const tilted=check('tilted_camera_frame',e=>!e.ok,{camMode:'orbit'});
  if(tilted.camera.q.some((v,i)=>Math.abs(v-[frd.w,frd.x,frd.y,frd.z][i])>1e-8))throw new Error('Tilted camera frame conversion');
  aim();
  camera.position.z=-95;camera.lookAt(0,-9.6,5);world.scenario.visibility_m=300;
  check('too_small',e=>!e.ok&&e.coverage<.0025);aim();world.scenario.visibility_m=3;state.silt=.9;
  check('fog_silt',e=>!e.ok&&e.reason.includes('能見度'));
  world.scenario.visibility_m=30;state.silt=0;
  const plate=new THREE.Mesh(new THREE.BoxGeometry(.6,.6,.1),new THREE.MeshStandardMaterial());plate.position.set(0,-9.6,3);scene.add(plate);
  check('engineering',e=>e.ok&&e.entity_id==='inspection-plate',{targets:[{entity_id:'inspection-plate',category:'engineering',mesh:plate}]});scene.remove(plate);plate.geometry.dispose();plate.material.dispose();
  environment.dispose();world.habitat={entities:[],fish_schools:[{id:'school-test',pos:[4,0,10],count:24,variant:0}]};environment=new Environment(scene,world);
  environment.update(.016,camera,null,state);
  check('actual_fish_instances',e=>e.ok&&e.entity_id==='school-test'&&e.visible_samples>3);
  const fishMesh=environment.sharedSchools[0].mesh;
  for(let i=0;i<fishMesh.count;i++){const matrix=new THREE.Matrix4();fishMesh.getMatrixAt(i,matrix);matrix.elements[12]+=25;fishMesh.setMatrixAt(i,matrix);}fishMesh.instanceMatrix.needsUpdate=true;
  check('fish_moved_offscreen',e=>!e.ok);
  camera.lookAt(25,-10,4);check('fish_current_matrix',e=>e.entity_id==='school-test');
  environment.dispose();world.habitat={entities:[{id:'kelp-test',kind:'kelp',variant:0,pos:[3,0,10],scale:1,yaw:0}],fish_schools:[]};environment=new Environment(scene,world);
  state.t=2.3;camera.position.set(0,-8.8,0);camera.lookAt(.2,-8.8,3);environment.update(.016,camera,new THREE.Vector3(.2,0,.1),state);
  check('shader_bent_kelp',e=>e.ok&&e.entity_id==='kelp-test');
  environment.dispose();
  world.habitat={entities:[{id:'seastar-test',kind:'seastar',variant:0,pos:[3,0,10],scale:.4,yaw:0}],fish_schools:[]};environment=new Environment(scene,world);
  camera.position.set(0,-8.8,1);camera.lookAt(0,-9.97,3);camera.updateMatrixWorld(true);
  check('actual_seastar',e=>e.ok&&e.entity_id==='seastar-test');environment.dispose();
  for(const realWorld of payload.worlds){
    const actualEnvironment=new Environment(scene,realWorld);
    const target=realWorld.habitat.entities.find(e=>['coral','seagrass'].includes(e.kind));
    const at=new THREE.Vector3(-target.pos[1],-target.pos[2]+.35,target.pos[0]);
    camera.position.copy(at).add(new THREE.Vector3(0,.2,-2));camera.lookAt(at);camera.updateMatrixWorld(true);
    actualEnvironment.update(.016,camera,null,{t:1,silt:0});renderer.render(scene,camera);
    const started=performance.now();
    const evidence=inspectObservation({scene,camera,environment:actualEnvironment,state:{silt:0},world:realWorld,camMode:'onboard'});
    results[realWorld.scenario.key]={...evidence,elapsed_ms:performance.now()-started,entity_count:realWorld.habitat.entities.length};
    actualEnvironment.dispose();
  }
  renderer.dispose();return results;
}
